[WARNING][2023-06-17 23:20:49][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[WARNING][2023-06-17 23:20:49][chatgpt.py:171] - proxy no find, directly request to chatgpt instead
[INFO][2023-06-17 23:20:49][victorinox.py:86] - use_tools=['url-get', 'meteo-weather', 'python', 'terminal'], params: {'debug': False, 'openai_api_key': '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', 'open_ai_api_base': 'https://api.openai.com/v1', 'proxy': '', 'request_timeout': 120, 'model_name': 'gpt-3.5-turbo', 'no_default': False, 'top_k_results': 3, 'news_api_key': '', 'bing_subscription_key': '', 'google_api_key': '', 'google_cse_id': '', 'searx_search_host': '', 'wolfram_alpha_appid': '', 'morning_news_api_key': '', 'cuda_device': 'cpu', 'think_depth': 3, 'arxiv_summary': True, 'morning_news_use_llm': False}
